services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/:/data
      - ./td/:/data/td
    env_file: "./node-red/.env"

  dashboard:
    container_name: nextapp
    image: nextapp
    build: ./dashboard
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
