services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/:/data
      - ./td/:/data/td

  dashboard:
    container_name: nextapp
    image: nextapp
    build: ./dashboard
    ports:
      - "3002:3002"
