services:
  node-red:
    image: nodered/node-red:latest
    build: ./apps/node-red
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    volumes:
      - ./apps/td/:/data/td
      - ./.env:/data/.env
    env_file: "./.env"

  dashboard:
    container_name: nextapp
    image: nextapp
    build:
      context: ./apps/dashboard
      args:
        API_AUTHORIZATION_TOKEN: ${API_AUTHORIZATION_TOKEN}
    ports:
      - "3000:3000"
    environment:
      - API_AUTHORIZATION_TOKEN=${API_AUTHORIZATION_TOKEN}

  nginx:
    container_name: nginx
    build: ./apps/nginx
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  semantic-app:
    build: ./apps/semantic
    ports:
      - "8080:8080"
    volumes:
      - ./apps/semantic/data:/app/data
    command: ["serve"]
    environment:
      - TZ=America/Sao_Paulo

  semantic-builder:
    build: ./apps/semantic
    volumes:
      - ./apps/semantic/data:/app/data
    command: ["build"]
    profiles: ["builder"] 
