services:
  wot-server:
    image: nodered/node-red:latest
    build: ./apps/wot-server
    environment:
      - TZ=America/Sao_Paulo
      - NODE_RED_CREDENTIAL_SECRET=agents-in-charge-secret-key-2024
    ports:
      - "1880:1880"
    volumes:
      - ./apps/td/:/data/td
      - ./apps/wot-server:/data
      - ./apps/td/:/data/td
      - /data/node_modules
    env_file: "./.env"

  dashboard:
    container_name: nextapp
    image: nextapp
    build:
      context: ./apps/dashboard
      args:
        NEXT_PUBLIC_API_AUTHORIZATION_TOKEN: ${API_AUTHORIZATION_TOKEN}
    ports:
      - "3000:3000"
    env_file: "./.env"

  nginx:
    container_name: nginx
    build: ./apps/nginx
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  semantic-app:
    build: ./apps/semantic
    ports:
      - "8080:8080"
    volumes:
      - ./apps/semantic/data:/app/data
    command: ["serve"]
    environment:
      - TZ=America/Sao_Paulo

  semantic-builder:
    build: ./apps/semantic
    volumes:
      - ./apps/semantic/data:/app/data
    command: ["build"]
    profiles: ["builder"] 

  opc-simulator:
    build: ./apps/opc-simulator
    ports:
      - "4840:4840" # OPC-UA Port
      - "4041:4041" # HTTP Port for adding pieces
    environment:
      - NODE_ENV=development
    profiles: ["dev"]
